apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999 # postgres user is id 999
        runAsGroup: 2000
        fsGroup: 2000
      containers:
      - name: postgresdb
        image: postgres
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: UUR
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdb
          - name: postgres-secrets
            mountPath: "/etc/postgres-secrets"
            readOnly: true 
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: uur-pvc
        - name: postgres-secrets
          secret: 
            secretName: postgres-secrets
   