apiVersion: v1
kind: PersistentVolume
metadata:
  name: uur-pv
  labels: 
    app: uur
spec:
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uur-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
