# Generated by Django 5.0.7 on 2024-07-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='contnet',
            new_name='content',
        ),
    ]
